---
title: "Spatial analysis adult gannets 2023"
author: "Aurore Ponchon"
format: html
editor: visual
---

# Separate kernels over infection and sex

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false

library(here)
library(tidyverse)
library(sf)
library(adehabitatHR)
library(rnaturalearth)
library(terra)
library(ggspatial)
library(RColorBrewer)

source(here::here("R","trip_functions.R"))
source(here::here("R","problem_trips.R"))

load(here("data","NewlyCreatedData","loc_clean_interp6_rouzic23.Rdata"))

ext.brit<-terra::ext(300000,650000,5270000,5650000)

mycol90<-turbo(n=2,begin=0.25, end=0.7)
mycol50<-turbo(n=2,begin=0.2, end=0.75)

#filter and project clean trips
locs<-loc.clean.interp.rouzic23 %>% 
    dplyr::mutate(sero=as.factor(sero),
                  sex=as.factor(sex),
                  deploy=as.factor(deploy)) %>% 
    dplyr::filter(!trip.id %in% migration & 
                      !trip.id %in% last.incomplete) %>% 
    sf::st_as_sf(., coords = c("long","lat")) %>% 
    sf::st_set_crs(4326) %>% 
    st_transform(., projcrs) %>% 
    as_Spatial(.)
rm(loc.clean.interp.rouzic)

#load bathymetry layer
bathym<-terra::rast(here::here("data",
                               "RawData",
                               "shapefiles",
                               "Bathym_FR_UK.tif")) %>% 
       terra::project(.,projcrs) %>% 
       terra::crop(., ext.brit)

bathym[bathym>0]<-0
ocean.pal <- rev(colorRampPalette(brewer.pal(9,"Blues"))(9))
zbreaks <- c(-500,-200,-150,-100,-50,-25,0)


#select borders
target<-c("France","United Kingdom","Spain","Belgium",
          "Netherlands", "Germany","Ireland","Isle of Man",
          "Jersey" ,"Guernsey"  ,"Åland")


#contours of countries
shp<-ne_countries(scale = 10, returnclass = 'sf') %>%
    dplyr::filter(name %in% target) %>% 
  st_transform(.,projcrs)  %>% 
    st_crop(., ext.brit)

#coastlines
coast<-ne_coastline(scale = 10, returnclass = "sf") %>% 
  st_transform(.,projcrs)  %>% 
    st_crop(., ext.brit)

coord_rouzic<-colo_coord_rouzic %>% 
    sf::st_as_sf(., coords = c("long","lat")) %>% 
    sf::st_set_crs(4326)


##kernels pour les sero
loc.inf<-subset(locs,locs$sero==1)
loc.noninf<-subset(locs,locs$sero==0)

KUD.sero.inf<- kernelUD(loc.inf[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.inf <- getvolumeUD(KUD.sero.inf)
ver90.sero.inf<-getverticeshr(KUD.sero.inf ,90) %>% 
    st_as_sf(.)
# ver75.sero.inf<-getverticeshr(KUD.sero.inf ,75)%>% 
#     st_as_sf(.)
ver50.sero.inf<-getverticeshr(KUD.sero.inf ,50)%>% 
    st_as_sf(.)
# ver25.sero.inf<-getverticeshr(KUD.sero.inf ,25)%>% 
#     st_as_sf(.)

KUD.sero.noninf<- kernelUD(loc.noninf[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.noninf <- getvolumeUD(KUD.sero.noninf)
ver90.sero.noninf<-getverticeshr(KUD.sero.noninf ,90) %>% 
    st_as_sf(.)
ver50.sero.noninf<-getverticeshr(KUD.sero.noninf ,50)%>% 
    st_as_sf(.)


kern.sero<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
     geom_sf(data=ver90.sero.noninf, fill=mycol90[1] ,
                             colour=NA ,
                             alpha=0.3) +
      geom_sf(data=ver90.sero.inf, fill=mycol90[2] ,
                             colour=NA,
                             alpha=0.3) + 
    geom_sf(data=ver50.sero.noninf, fill=mycol50[1] ,
                             colour=NA ,
                             alpha=0.5) +
    geom_sf(data=ver50.sero.inf, fill=mycol50[2],
                             colour=NA,
                             alpha=0.5) +
    geom_sf(data=shp,fill="grey90") +
    geom_sf(data=coast) +
    geom_sf(data = coord_rouzic,
            shape=23, 
            colour="black",
            fill="yellow", 
            size=4) + 
    labs(title="Distribution infected vs uninfected") +
    coord_sf(xlim=ext.brit[c(1,2)],
             ylim=ext.brit[c(3,4)],
             expand=F) +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw() 



tiff(here::here("outputs","adults_distribution_kernel_sero.tif"),
     width=3500,
     height=3500,
     res=500,
     compression="lzw")
print(kern.sero)
dev.off()


mycol2.50<-magma(n=2,begin=0.25,end=0.75)
mycol2.90<-magma(n=2,begin=0.3,end=0.7)

##kernels for sex
loc.fem<-subset(locs,locs$sex=="F")
loc.mal<-subset(locs,locs$sex=="M")

KUD.sero.mal<- kernelUD(loc.mal[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.mal <- getvolumeUD(KUD.sero.mal)
ver90.sero.mal<-getverticeshr(KUD.sero.mal ,90) %>% 
    st_as_sf(.)
# ver75.sero.mal<-getverticeshr(KUD.sero.mal ,75)%>% 
#     st_as_sf(.)
ver50.sero.mal<-getverticeshr(KUD.sero.mal ,50)%>% 
    st_as_sf(.)
# ver25.sero.mal<-getverticeshr(KUD.sero.mal ,25)%>% 
#     st_as_sf(.)

KUD.sero.fem<- kernelUD(loc.fem[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.fem <- getvolumeUD(KUD.sero.fem)
ver90.sero.fem<-getverticeshr(KUD.sero.fem ,90) %>% 
    st_as_sf(.)
# ver75.sero.fem<-getverticeshr(KUD.sero.fem ,75)%>% 
#     st_as_sf(.)
ver50.sero.fem<-getverticeshr(KUD.sero.fem ,50)%>% 
    st_as_sf(.)
# ver25.sero.fem<-getverticeshr(KUD.sero.fem ,25)%>% 
#     st_as_sf(.)



  kern.sex<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
    geom_sf(data=ver90.sero.fem, fill=mycol2.90[1] ,
                             colour=NA,
                             alpha=0.2) + 
      geom_sf(data=ver90.sero.mal, fill=mycol2.90[2] ,
                             colour=NA ,
                             alpha=0.2) +
         geom_sf(data=ver50.sero.fem, fill=mycol2.50[1],
                             colour=NA,
                             alpha=0.6) +
    geom_sf(data=ver50.sero.mal, fill=mycol2.50[2] ,
                             colour=NA ,
                             alpha=0.6) +

    geom_sf(data=shp,fill="grey90") +
    geom_sf(data=coast) +
    geom_sf(data = coord_rouzic,
            shape=23, 
            colour="black",
            fill="yellow", 
            size=4) + 
    coord_sf(xlim=ext.brit[c(1,2)],
             ylim=ext.brit[c(3,4)],
             expand=F) +
  labs(title="Distribution males vs females") +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw() 

  tiff(here::here("outputs","adults_distribution_kernel_sex.tif"),
     width=3500,
     height=3500,
     res=500,
     compression="lzw")

print(kern.sex)

dev.off()


##kernels for sex over time (by month)

maxjuil<-as.POSIXct(strptime("2023-07-31 23:59:59",
                             format="%F %H:%M:%S"),time="tz")
maxaout<-as.POSIXct(strptime("2023-08-31 23:59:59",
                             format="%F %H:%M:%S"),time="tz")

loc.fem.juil<-subset(locs,locs$sex=="F" & locs$datetime <= maxjuil)
loc.fem.aout<-subset(locs,locs$sex=="F" & 
                         locs$datetime > maxjuil & 
                         locs$datetime <= maxaout)
loc.fem.sept<-subset(locs,locs$sex=="F" & locs$datetime > maxaout)
loc.mal.juil<-subset(locs,locs$sex=="M" & locs$datetime <= maxjuil)
loc.mal.aout<-subset(locs,locs$sex=="M" & 
                         locs$datetime <= maxaout & 
                         locs$datetime > maxjuil)
loc.mal.sept<-subset(locs,locs$sex=="M" & locs$datetime > maxaout)

KUD.sero.mal.juil<- kernelUD(loc.mal.juil[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.mal.juil <- getvolumeUD(KUD.sero.mal.juil)
ver90.sero.mal.juil<-getverticeshr(KUD.sero.mal.juil ,90) %>% 
    st_as_sf(.)
ver50.sero.mal.juil<-getverticeshr(KUD.sero.mal.juil ,50)%>% 
    st_as_sf(.)

KUD.sero.mal.aout<- kernelUD(loc.mal.aout[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.mal.aout <- getvolumeUD(KUD.sero.mal.aout)
ver90.sero.mal.aout<-getverticeshr(KUD.sero.mal.aout ,90) %>% 
    st_as_sf(.)
ver50.sero.mal.aout<-getverticeshr(KUD.sero.mal.aout ,50)%>% 
    st_as_sf(.)

KUD.sero.mal.sept<- kernelUD(loc.mal.sept[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.mal.sept <- getvolumeUD(KUD.sero.mal.sept)
ver90.sero.mal.sept<-getverticeshr(KUD.sero.mal.sept ,90) %>% 
    st_as_sf(.)
ver50.sero.mal.sept<-getverticeshr(KUD.sero.mal.sept ,50)%>% 
    st_as_sf(.)

#females
KUD.sero.fem.juil<- kernelUD(loc.fem.juil[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.fem.juil <- getvolumeUD(KUD.sero.fem.juil)
ver90.sero.fem.juil<-getverticeshr(KUD.sero.fem.juil ,90) %>% 
    st_as_sf(.)
ver50.sero.fem.juil<-getverticeshr(KUD.sero.fem.juil ,50)%>% 
    st_as_sf(.)

KUD.sero.fem.aout<- kernelUD(loc.fem.aout[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.fem.aout <- getvolumeUD(KUD.sero.fem.aout)
ver90.sero.fem.aout<-getverticeshr(KUD.sero.fem.aout ,90) %>% 
    st_as_sf(.)
ver50.sero.fem.aout<-getverticeshr(KUD.sero.fem.aout ,50)%>% 
    st_as_sf(.)

KUD.sero.fem.sept<- kernelUD(loc.fem.sept[,"site"],
                    same4all=T,
                    h=10000,
                    grid=1000)
KUD.sero.fem.sept <- getvolumeUD(KUD.sero.fem.sept)
ver90.sero.fem.sept<-getverticeshr(KUD.sero.fem.sept ,90) %>% 
    st_as_sf(.)
ver50.sero.fem.sept<-getverticeshr(KUD.sero.fem.sept ,50)%>% 
    st_as_sf(.)


  kern.sex.juil<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
    geom_sf(data=ver90.sero.fem.juil, fill=mycol2.90[1] ,
                             colour=NA,
                             alpha=0.2) + 
      geom_sf(data=ver90.sero.mal.juil, fill=mycol2.90[2] ,
                             colour=NA ,
                             alpha=0.2) +
         geom_sf(data=ver50.sero.fem.juil, fill=mycol2.50[1],
                             colour=NA,
                             alpha=0.6) +
    geom_sf(data=ver50.sero.mal.juil, fill=mycol2.50[2] ,
                             colour=NA ,
                             alpha=0.6) +

    geom_sf(data=shp,fill="grey90") +
    geom_sf(data=coast) +
    geom_sf(data = coord_rouzic,
            shape=23, 
            colour="black",
            fill="yellow", 
            size=4) + 
    coord_sf(xlim=ext.brit[c(1,2)],
             ylim=ext.brit[c(3,4)],
             expand=F) +
  labs(title="July 2023") +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw() 

  
    kern.sex.aout<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
    geom_sf(data=ver90.sero.fem.aout, fill=mycol2.90[1] ,
                             colour=NA,
                             alpha=0.2) + 
      geom_sf(data=ver90.sero.mal.aout, fill=mycol2.90[2] ,
                             colour=NA ,
                             alpha=0.2) +
         geom_sf(data=ver50.sero.fem.aout, fill=mycol2.50[1],
                             colour=NA,
                             alpha=0.6) +
    geom_sf(data=ver50.sero.mal.aout, fill=mycol2.50[2] ,
                             colour=NA ,
                             alpha=0.6) +

    geom_sf(data=shp,fill="grey90") +
    geom_sf(data=coast) +
    geom_sf(data = coord_rouzic,
            shape=23, 
            colour="black",
            fill="yellow", 
            size=4) + 
    coord_sf(xlim=ext.brit[c(1,2)],
             ylim=ext.brit[c(3,4)],
             expand=F) +
  labs(title="August 2023") +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw() 
    
       kern.sex.sept<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
    geom_sf(data=ver90.sero.fem.sept, fill=mycol2.90[1] ,
                             colour=NA,
                             alpha=0.2) + 
      geom_sf(data=ver90.sero.mal.sept, fill=mycol2.90[2] ,
                             colour=NA ,
                             alpha=0.2) +
         geom_sf(data=ver50.sero.fem.sept, fill=mycol2.50[1],
                             colour=NA,
                             alpha=0.6) +
    geom_sf(data=ver50.sero.mal.sept, fill=mycol2.50[2] ,
                             colour=NA ,
                             alpha=0.6) +

    geom_sf(data=shp,fill="grey90") +
    geom_sf(data=coast) +
    geom_sf(data = coord_rouzic,
            shape=23, 
            colour="black",
            fill="yellow", 
            size=4) + 
    coord_sf(xlim=ext.brit[c(1,2)],
             ylim=ext.brit[c(3,4)],
             expand=F) +
  labs(title="Sept 2023") +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw()  
    
  tiff(here::here("outputs","adults_distribution_kernel_sex_time.tif"),
     width=6000,
     height=3000,
     res=500,
     compression="lzw")

grid.arrange(kern.sex.juil,kern.sex.aout,kern.sex.sept,
             nrow=1,ncol=3)

dev.off()




path<-locs %>% 
    as.data.frame()

ext.brit<-terra::ext(300000,700000,5200000,5680000)

##paths sero
path.sero<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
     geom_path(data=path, aes(x=coords.x1, y=coords.x2,
                              colour=sero), alpha=0.5) +
    geom_sf(data=shp,fill="grey90") +
    geom_sf(data=coast) +
    geom_sf(data = coord_rouzic,
            shape=23, 
            colour="black",
            fill="yellow", 
            size=4) + 
  #  labs(title="Distribution infected vs uninfected") +
    coord_sf(xlim=ext.brit[c(1,2)],
             ylim=ext.brit[c(3,4)],
             expand=F) +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw() 

print(path.sero)

tiff(here::here("outputs","adults_distribution_kernel_sero.tif"),
     width=3500,
     height=3500,
     res=500,
     compression="lzw")
print(path.sero)
dev.off()



```

# GIF animation

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false

library(gganimate)

#define an extent for study area
    xmin<-240000
    xmax<-830000
    ymin<-5190000
    ymax<-5620000



loc_df<-as.data.frame(locs) %>%
    dplyr::rename(long=coords.x1,
            lat=coords.x2)
    # dplyr::filter(id=="233659"| id=="235197")

nb<-length(unique(loc_df$id))

#contours of countries
shp<-ne_countries(scale = 10, returnclass = 'sf') %>%
    dplyr::filter(name %in% target) %>%
  st_transform(.,projcrs)  %>%
    st_crop(., ext(c(xmin,xmax,ymin,ymax)))

#coastlines
coast<-ne_coastline(scale = 10, returnclass = "sf") %>%
  st_transform(.,projcrs) %>%
    st_crop(., ext(c(xmin,xmax,ymin,ymax)))


anim <- ggplot()+

  # basemap
  geom_sf(data = shp)+
     geom_sf(data = coast)+

  coord_sf(xlim=c(xmin,xmax),
             ylim=c(ymin,ymax),
             expand=F) +
  # lines and points
  geom_path(data = loc_df,
            aes(x=long,y=lat,
                group=id,
                color=id),
                 show.legend = FALSE,
            alpha = 0.3)+
  geom_point(data = loc_df,
             aes(x=long,y=lat,
                 group=id,
                 fill=id),
             show.legend = FALSE,
             alpha = 0.7,
             shape=21,
             size = 2)+
  scale_fill_manual(values=magma(nb)) +
    scale_colour_manual(values=magma(nb)) +

  # formatting
  labs(x=NULL, y=NULL,
       fill = 'Sex',
       color = 'Sex')+
  theme_minimal()+
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
  theme(legend.position = "none")

print(anim)


animgif = anim +
  transition_reveal(along = datetime) +
#  ease_aes('linear') +
  ggtitle("Date:{frame_along}")

gganimate::animate(animgif, nframes = 800, fps = 25,
                   renderer = gifski_renderer(),
                   height=8,
                   width=4,
                   res=400,
                   units="in")
gganimate::anim_save(here::here("outputs","tracks.gif"))
```
