---
title: "6-Comparison all trips 2005-2023"
author: "Aurore Ponchon"
format: html
editor: visual
---

# 1. Import all processed data

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false


library(here)
library(tidyverse)
library(sf)
library(kableExtra)
library(readxl)
library(grid)
library(gridExtra)
library(viridis)

source(here::here("R","trip_functions.R"))

load(here::here("data","NewlyCreatedData",
                "clean_2_locs_AD_rouzic2005-2019.RData"))
load(here::here("data","NewlyCreatedData",
                "clean_6_locs_AD_rouzic23.RData"))
load(here::here("data","NewlyCreatedData",
                "clean_locs_rouzic_2022.RData"))


rouz05.19<-cleanLocs.rouzic05.19 %>% 
    dplyr::select(id,datetime,long,lat,
                  distmax,distadj,totalpath,difftimemin,travelNb,
           onlandNb,trip.id) %>% 
    mutate(year=year(datetime)) 


rouz23<-cleanLocs.rouzic23 %>% 
    dplyr::select(id,datetime,long,lat,
                  distmax,distadj,totalpath,difftimemin,travelNb,
           onlandNb,trip.id) %>% 
     mutate(year=year(datetime)) 

#Identification of trips to exclude (incomplete trips and migration trip)
incomplete.2022<-c("222267.1","222267.6","222275.1","222276.1",
              "222279.8","222279.32","222280.45","222269.17","222270.32","222271.25","222272.24","222273.22","222274.25","222275.28","222276.17","222277.10","222278.1","222279.33","222280.46","222281.7")


rouz22<-cleanLocs.rouzic %>% 
    dplyr::filter(!trip.id %in% incomplete.2022) %>% 
    dplyr::select(id,datetime,long,lat,
                  distmax,distadj,totalpath,difftimemin,travelNb,
           onlandNb,trip.id) %>% 
     mutate(year=year(datetime)) 


rouz.all1<-rbind(rouz05.19,rouz22,rouz23) 


metadata<-read_excel(here("data","RawData","metadata_2005-2023.xlsx"),
              sheet="Feuil1",col_names = T) 

rouz.all<-rouz.all1%>% 
    left_join(.,metadata,by=c("year","id")) %>% 
    dplyr::mutate(id=as.factor(id),
                  trip.id=as.factor(trip.id),
                  sero=as.factor(sero)) %>% 
    dplyr::arrange(year,id,datetime)


all.trips<- rouz.all %>% 
    trips_summary_ind(.,
                      colony=colo_coord_rouzic) %>% 
     mutate(across(c(id, trip.id, sex ), as.factor)) %>% 
    mutate(year=year(DateEnd)) %>% 
    dplyr::filter(travelNb>0) %>% 
     mutate(year=as.factor(year),
           Date=as.numeric(format(DateEnd,format="%j")))

all.land<-rouz.all %>% 
    land_summary_ind(.,
                      colony=colo_coord_rouzic) %>% 
    dplyr::filter(LandDurh > 1 & 
                    LandDurh < 100 & 
                      stage=="adult")
```

# 2- Map of all trips

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false

library(rnaturalearth)
library(ggspatial)


#select borders
target<-c("France","United Kingdom","Spain","Belgium",
          "Netherlands", "Germany","Ireland","Isle of Man",
          "Jersey" ,"Guernsey"  ,"Åland")  

coord_rouzic<-colo_coord_rouzic %>% 
    sf::st_as_sf(., coords = c("long","lat"),crs=wgscrs)  
  

indi23<-rouz.all %>% 
    dplyr::filter(year==2023)


 indisf.all<-rouz.all1 %>%
     mutate(year=factor(as.factor(year),
                        levels=c(2023,2022,2019,2017,2016,2015,2014,
                                 2013,2012, 2011,2010, 2006,2005)) )
     
 
 #contours of countries
shp<-ne_countries(scale = 10, returnclass = 'sf') %>%
    dplyr::filter(name %in% target) 
    

#coastlines
coast<-ne_coastline(scale = 10, returnclass = "sf")

colinfect<-viridis(n=2,begin=0,end=0.6,option="D")

colinfect

 #Map of all locations for 2023
   map.year23<-ggplot()+
            geom_path(data = indi23,
            aes(x=long,y=lat,
                group=year,
                color=sero),
                 show.legend = T,
            alpha=0.4) +
       geom_sf(data=shp,fill="grey90") +
           geom_sf(data = coord_rouzic,
            shape=23,
            colour="black",
            fill="yellow",
            size=4) +
        coord_sf(xlim=c(-9,2),
             ylim=c(46.8,52.0),
             expand=F) +
   scale_colour_manual(values=colinfect,  name="Eye") +
       labs(x="",y="") +
     annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
       theme_bw()

   print(map.year23)
   

 #Map of all locations for all years
   map.allyears<-ggplot()+
            geom_path(data = indisf.all,
            aes(x=long,y=lat,
                group=year,
                color=year),
                 show.legend = T,
            alpha=0.4) +
       geom_sf(data=shp,fill="grey90") +
           geom_sf(data = coord_rouzic,
            shape=23,
            colour="black",
            fill="yellow",
            size=4) +
        coord_sf(xlim=c(-9,2),
             ylim=c(46.8,52.0),
             expand=F) +
   scale_colour_manual(values=turbo(13),  name="Year") +
       labs(x="",y="") +
     annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
       theme_bw()

   
   
    #create external files
tiff(here::here("outputs","Clean_trips_2005-2023.png"),
        width=4000,height=3000,res=400,
     compression="lzw")

  

print(map.allyears)

dev.off()

```

# 3. Trip characteristics 2005-2023

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false


#Table summary
sum.ids<-all.trips %>% 
    group_by(year) %>% 
    summarize(Ids=length(unique(id)),
              Trips=length(unique(trip.id)),
              Debut=min(DateStart),
              Fin=max(DateEnd))
  
kbl(sum.ids,caption="Sample size for trips") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))



sum.id<- all.trips %>% 
    group_by(year,id) %>% 
    summarize(across(c(Distmaxkm, TripDurh, TotalPathkm), 
                     ~ mean(.x, na.rm = TRUE))) %>% 
    as.data.frame()

sum.trips1<- sum.id %>% 
    group_by(year) %>% 
    summarize(across(where(is.numeric), 
                     list(Mean=mean,
                          SE=plotrix::std.error,
                          Min=min,
                          Max=max))) %>% 
    mutate(across(where(is.numeric), round,digits=1))


sum.trips<-sum.trips1 %>% 
           dplyr::mutate(MeanDist=paste(Distmaxkm_Mean,Distmaxkm_SE,sep=" ± "),
                         DistRange=paste(Distmaxkm_Min,Distmaxkm_Max,sep=" - "),
                         MeanDur=paste(TripDurh_Mean,TripDurh_SE,sep=" ± "),
                         DurRange=paste(TripDurh_Min,TripDurh_Max,sep=" - "),     
                         MeanPath=paste(TotalPathkm_Mean,TotalPathkm_SE,sep=" ± "),
                      PathRange=paste(TotalPathkm_Min,TotalPathkm_Max,sep=" - ")) %>%
        dplyr::select(-c(2:13)) %>% 
    ungroup()

# lands.ids<-land %>% 
#     summarize(Ids=length(unique(id)),
#               Land=length(unique(onland.id)),
#               Debut=min(DateEnd),
#               Fin=max(DateEnd))
# 
# kbl(lands.ids,caption="Sample size for periods on land") %>%
#   kable_styling(bootstrap_options = c("striped", "hover"))
# 
# land.id<- land %>%
#     group_by(id) %>%
#     summarize(Time= mean(LandDurh, na.rm=T)) %>%
#     as.data.frame()

# sum.lands<- land.id %>%
#     summarize(across(where(is.numeric),
#                      list(mean=mean,
#                           se=plotrix::std.error))) %>%
#     mutate(across(where(is.numeric), round,digits=1))

kbl(sum.trips,caption="Summary of trip characteristics",
    col.names=c("Year",
                "Maximal distance (km)",
                "Maximal distance (km)",
                "Trip Duration (h)",
                "Trip Duration (h)",
                "Total path (km)",
                "Total path (km)")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

# kbl(sum.lands,caption="Summary of nest attendance",
#     col.names=c("DurationMean","DurationSE")) %>%
#   kable_styling(bootstrap_options = c("striped", "hover"))


```

# Comparison between years

```{r}

library(plotrix)

nb.ind<-read_excel(here::here("data","RawData","Effectif.xlsx")) %>% 
    dplyr::mutate(count=count/1000) %>% 
    dplyr::rename("YearN"="year")

# 
# all.trips.num<-all.trips %>% 
#dplyr::mutate(YearN=as.numeric(year))
#     left_join(.,nb.ind,by="YearN")

summytrips<-sum.trips1 %>% 
    dplyr::mutate(YearN=as.numeric(as.character(year))) %>% 
    left_join(.,nb.ind,by="YearN")

# mycol2<-c(magma(n=length(unique(all.trips$year)),begin=0.15,end=0.9),rep("black",7))
mycol2<-c(turbo(n=length(unique(all.trips$year))),rep("black",7))


coef<-9
#maximal distance
dist.year<-ggplot(summytrips,aes(x=YearN)) +
    #  geom_jitter(aes(color=year),width=0.2,alpha=0.7) +
    # geom_boxplot(aes(color=year,fill=year),
    #              outlier.alpha = 0, 
    #              alpha=0.2, 
    #              show.legend = FALSE)+
    geom_point(aes(x=YearN,y=Distmaxkm_Mean,color=year),
               pch=16,
               size=3) +
    geom_errorbar(aes(x=YearN,
                      ymin=Distmaxkm_Mean-Distmaxkm_SE,
                      ymax=Distmaxkm_Mean+Distmaxkm_SE,
                      colour=year),
                  width = 0) +
    geom_point(data=nb.ind, aes(x=YearN, y=count*9),
               shape=17,
               size=2,
               show.legend = F) +
    geom_line(data=nb.ind,aes(x=YearN, y=count*9),
              show.legend=F) +
    scale_y_continuous(name = "Maximal distance to the colony (km)",
                       limits=c(0,225),expand = c(0.001,0.001),
                       breaks=seq(0,225,25),
                       sec.axis = sec_axis(~./9, name="Colony size (x1000 ind)")) +
    scale_x_continuous(limits=c(2002,2024),breaks=seq(2003,2023,5),
                       expand=c(0.001,0.001))+
    labs(y="",tag="a)",x="") +
     scale_colour_manual(values=mycol2, name="Year")  +
    theme(text = element_text(size=10),
          axis.text = element_text(size=10),
          legend.text = element_text(size=10),
          axis.title.x=element_blank())
print(dist.year)


#trip duration
coeff<-2
#maximal distance
dur.year<-ggplot(summytrips,aes(x=YearN)) +
    #  geom_jitter(aes(color=year),width=0.2,alpha=0.7) +
    # geom_boxplot(aes(color=year,fill=year),
    #              outlier.alpha = 0, 
    #              alpha=0.2, 
    #              show.legend = FALSE)+
    geom_point(aes(x=YearN,y=TripDurh_Mean,color=year),
               pch=16,
               size=3) +
    geom_errorbar(aes(x=YearN,
                      ymin=TripDurh_Mean-TripDurh_SE,
                      ymax=TripDurh_Mean+TripDurh_SE,
                      colour=year),
                  width = 0) +
    geom_point(data=nb.ind, aes(x=YearN, y=count*coeff),
               shape=17,
               size=2,
               show.legend = F) +
    geom_line(data=nb.ind,aes(x=YearN, y=count*coeff),
              show.legend=F) +
    scale_y_continuous(name = "Trip Duration (h)",
                       limits=c(0,50),expand = c(0.001,0.001),
                       breaks=seq(0,50,10),
                       sec.axis = sec_axis(~./coeff, name="Colony size (x1000 ind)")) +
    scale_x_continuous(limits=c(2002,2024),breaks=seq(2003,2023,5),
                       expand=c(0.001,0.001))+
    labs(y="",tag="b)",x="") +
    scale_colour_manual(values=mycol2, name="Year")  +
    theme(text = element_text(size=10),
          axis.text = element_text(size=10),
          legend.text = element_text(size=10),
          axis.title.x=element_blank())
print(dur.year)

#total distance travelled
coeff2<-35
tot.year<-ggplot(summytrips,aes(x=YearN)) +
    #  geom_jitter(aes(color=year),width=0.2,alpha=0.7) +
    # geom_boxplot(aes(color=year,fill=year),
    #              outlier.alpha = 0, 
    #              alpha=0.2, 
    #              show.legend = FALSE)+
    geom_point(aes(x=YearN,y=TotalPathkm_Mean,color=year),
               pch=16,
               size=3) +
    geom_errorbar(aes(x=YearN,
                      ymin=TotalPathkm_Mean-TotalPathkm_SE,
                      ymax=TotalPathkm_Mean+TotalPathkm_SE,
                      colour=year),
                  width = 0) +
    geom_point(data=nb.ind, aes(x=YearN, y=count*coeff2),
               shape=17,
               size=2,
               show.legend = F) +
    geom_line(data=nb.ind,aes(x=YearN, y=count*coeff2),
              show.legend=F) +
    scale_y_continuous(name = "Total distance travelled (km)",
                       limits=c(0,800),expand = c(0.001,0.001),
                       breaks=seq(0,800,200),
                       sec.axis = sec_axis(~./coeff2, name="Colony size (x1000 ind)")) +
    scale_x_continuous(limits=c(2002,2024),breaks=seq(2003,2023,5),
                       expand=c(0.001,0.001))+
    labs(y="",tag="c)",x="") +
    scale_colour_manual(values=mycol2, name="Year")  +
    theme(text = element_text(size=10),
          axis.text = element_text(size=10),
          legend.text = element_text(size=10),
          axis.title.x=element_blank())
print(tot.year)

mylegendyear<-g_legend(tot.year)


tiff(here("outputs","Trip_characteristics_2005_2023_mean.tif"),
     width=7000,
     height=4000,
     res=600,
     compression="lzw")
grid.arrange(arrangeGrob(dist.year+ theme(legend.position="none"),
                         dur.year+ theme(legend.position="none"),
                         tot.year+ theme(legend.position="none"),
                 #        att.sex+ theme(legend.position="none") ,
                                     ncol=3),
               mylegendyear, ncol=2,widths=c(1,0.1)) 

    dev.off()  
    
    

# col.dist<-ggplot(all.trips.num, aes(x=count,y=Distmaxkm,group=year))+
#      geom_point(aes(x=count,y=Distmaxkm,color=year),width=0.2)
#   #  geom_boxplot(aes(fill=year),width=0.5)

#print(col.dist)


#nest attendance
# land<-land %>% 
#     dplyr::mutate(sero=as.factor(sero))
# 
# att.sex<-ggplot(land,aes(x=sex,y=LandDurh,
#                      fill=sex, colour=sex))+
#       geom_violin(trim=FALSE, alpha=0.2)+
#   geom_jitter(width=0.2) +
#   geom_boxplot(outlier.alpha = 0, alpha=0.3, show.legend = FALSE) +
#   labs(y="Nest attendance (hrs)",x="",tag="d)") +
#   scale_y_continuous(limits=c(0,60),expand=c(0.01,0.01))+
#   scale_fill_manual(values=mycol2)  +
#   scale_colour_manual(values=mycol2)+
#   theme(legend.position = "none",
#       text = element_text(size=10),
#         axis.text = element_text(size=10),
#         axis.title.x=element_blank())

    
    
```

# Stats 2005-2023 with all data

```{r}
library(nlme)
library(emmeans)
library(DHARMa)
library(sjPlot)
library(ggeffects)

mycol<-turbo(13)

#1) GLMM on maximal distance to the colony

#get new dataframe for predictions with days and year
newdatrouz<-expand.grid(day=seq(min(all.trips$Date),
                                max(all.trips$Date),1),
                        year=as.factor(unique(all.trips$year)))
#glme on distance
glmm.dist.lme.rouz<-lme(log(Distmaxkm) ~ year + Date , 
                        random=~1 | (id) ,
                        data=all.trips)

summary(glmm.dist.lme.rouz)

#check effects
plot_model(glmm.dist.lme.rouz,sort.est = TRUE,show.values = TRUE)
ggpredict(glmm.dist.lme.rouz, terms = "year", type="fe")%>% plot()
ggpredict(glmm.dist.lme.rouz, terms = "Date", type="fe")%>% plot()

#estimate predicted values on dates and year
grouzdatedist <- ref_grid(glmm.dist.lme.rouz, 
                  cov.keep= c('year',"Date"))
emmrouzdatedist <- data.frame(emmeans(grouzdatedist, 
                              spec= c('year',"Date"), 
                              level= 0.95))

#plot intra-year effect on days according to year
distdate<-ggplot(data=emmrouzdatedist,aes(x=Date,y=exp(emmean)), group=year ) +
     geom_ribbon(data=emmrouzdatedist,aes( x=Date,
                                 ymin=exp(lower.CL),
                                 ymax=exp(upper.CL),
                                 fill=year),
                            alpha=0.2,colour = NA) +
  geom_point(data=all.trips, aes(x=Date,y=Distmaxkm,color=year),
              alpha=0.7,
              shape=16,
              show.legend=T) +
  geom_line(data=emmrouzdatedist,aes(x=Date,y=exp(emmean),color=year),
             show.legend = F,
            linewidth=2) +
  
  scale_y_continuous(limits=c(0,400),
                     breaks=seq(0,400,50),
                     expand=c(0.01,0.01))+
    scale_x_continuous(limits=c(150,300),
                       breaks=seq(150,300,25),
                       expand=c(0.001,0.001))+
  labs(y="Predicted maximal distance (km)",tag="a)",x="") +
  scale_colour_manual(values=mycol) +
  scale_fill_manual(values=mycol) +
  theme_light() +
  theme(#legend.position="none",
        panel.grid.minor = element_blank()) 

print(distdate)


#2) GLMM on trip duration

#glme on duration
glmm.dur.lme.rouz<-lme(log(TripDurh) ~ year + Date, 
                        random=~1 | id , 
                        data=all.trips)

plot(glmm.dur.lme.rouz)

#check effects
plot_model(glmm.dur.lme.rouz,sort.est = TRUE,show.values = TRUE)
ggpredict(glmm.dur.lme.rouz, terms = "year", type="fe")%>% plot()

#estimate predicted values on dates and year
grouzdatedur <- ref_grid(glmm.dur.lme.rouz, 
                  cov.keep= c('year',"Date"))
emmrouzdatedur <- data.frame(emmeans(grouzdatedur, 
                              spec= c('year',"Date"), 
                              level= 0.95))

#plot intra-year effect on days according to year
durdate<-ggplot(data=emmrouzdatedur,aes(x=Date,y=exp(emmean)), group=year ) +
     geom_ribbon(data=emmrouzdatedur,aes( x=Date,
                                 ymin=exp(lower.CL),
                                 ymax=exp(upper.CL),
                                 fill=year),
                            alpha=0.2,colour = NA) +
  geom_point(data=all.trips, aes(x=Date,y=TripDurh,color=year),
              alpha=0.7,
              shape=16,
              show.legend=T) +
  geom_line(data=emmrouzdatedur,aes(x=Date,y=exp(emmean),color=year),
             show.legend = F,
            linewidth=2) +
  
  scale_y_continuous(limits=c(0,200),
                     breaks=seq(0,200,50),
                     expand=c(0.01,0.01))+
    scale_x_continuous(limits=c(150,300),
                       breaks=seq(150,300,25),
                       expand=c(0.001,0.001))+
  labs(y="Predicted trip duration (h)",tag="b)",x="") +
  scale_colour_manual(values=mycol) +
  scale_fill_manual(values=mycol) +
  theme_light() +
  theme(#legend.position="none",
        panel.grid.minor = element_blank()) 

print(durdate)


#3) GLMM on total distance

#glme on duration
glmm.tot.lme.rouz<-lme(log(TotalPathkm) ~ year + Date, 
                        random=~1 | id , 
                        data=all.trips)

plot(glmm.tot.lme.rouz)

#check effects
plot_model(glmm.tot.lme.rouz,sort.est = TRUE,show.values = TRUE)
ggpredict(glmm.tot.lme.rouz, terms = "year", type="fe")%>% plot()

#estimate predicted values on dates and year
grouzdatetotpath <- ref_grid(glmm.tot.lme.rouz, 
                  cov.keep= c('year',"Date"))
emmrouzdatetotpath <- data.frame(emmeans(grouzdatetotpath, 
                              spec= c('year',"Date"), 
                              level= 0.95))

#plot intra-year effect on days according to year
totpathdate<-ggplot(data=emmrouzdatetotpath,aes(x=Date,y=exp(emmean)), 
                    group=year ) +
     geom_ribbon(data=emmrouzdatetotpath,aes( x=Date,
                                 ymin=exp(lower.CL),
                                 ymax=exp(upper.CL),
                                 fill=year),
                            alpha=0.2,colour = NA) +
  geom_point(data=all.trips, aes(x=Date,y=TotalPathkm,color=year),
              alpha=0.7,
              shape=16,
              show.legend=T) +
  geom_line(data=emmrouzdatetotpath,aes(x=Date,y=exp(emmean),color=year),
             show.legend = F,
            linewidth=2) +
  
  scale_y_continuous(limits=c(0,1400),
                     breaks=seq(0,1400,200),
                     expand=c(0.01,0.01))+
    scale_x_continuous(limits=c(150,300),
                       breaks=seq(150,300,25),
                       expand=c(0.001,0.001))+
  labs(y="Total distance per trip (km)",tag="c)",x="") +
  scale_colour_manual(values=mycol) +
  scale_fill_manual(values=mycol) +
  theme_light() +
  theme(#legend.position="none",
        panel.grid.minor = element_blank()) 

print(totpathdate)


mylegendyear<-g_legend(totpathdate)

tiff(here::here("outputs","Predictions_trip_characteristics_2005-2023_Jday.png"),
        width=4000,height=6000,res=400,
     compression="lzw")

grid.arrange(arrangeGrob(distdate+theme(legend.position="none"),
             durdate+theme(legend.position="none"),
             totpathdate+theme(legend.position="none"),
             nrow=3),
             mylegendyear, ncol=2,widths=c(1,0.1)) 
dev.off()


```

# Correlation with colony size

```{r}
####
###LME with colony size


dist.col.lme.rouz<-lme(log(Distmaxkm) ~ count, 
                       random=~1 | id , 
                       data=summytrips)
distcol.lme <- ref_grid(dist.col.lme.rouz, 
                        cov.keep= "count")
emmdistcol <- data.frame(emmeans(distcol.lme, 
                                 spec= "count", 
                                 level= 0.95))





#plot colony effect on trips
distcol<-ggplot(data=emmdistcol,aes(x=count,y=exp(emmean)) ) +
    geom_point(data=summytrips,aes(x=count,y=Distmaxkm,color=year),
               shape=16,alpha=0.5)+
    geom_line(size=1.5) +
    geom_ribbon(data=emmdistcol,aes( x=count,
                                     ymin=exp(lower.CL),
                                     ymax=exp(upper.CL)),
                alpha=0.3,colour = NA) +
    scale_y_continuous(limits=c(0,400),
                       breaks=seq(0,400,100),
                       expand=c(0.01,0.01))+
    scale_x_continuous(limits=c(11, 23),
                       breaks=seq(11,23,4),
                       expand=c(0.01,0.01))+
    labs(y="Maximal distance to the colony (km)",
         tag="a)",
         x="") +
    scale_colour_manual(values=mycol) +
    # scale_fill_manual(values=mycol) +
    theme_light() +
    theme(#legend.position="none",
        panel.grid.minor = element_blank()) 

print(distcol)

#plot colony effect on trips

dur.col.lme.rouz<-lme(log(TripDurh) ~ count, 
                      random=~1 | id , 
                      data=summytrips)
durcol.lme <- ref_grid(dur.col.lme.rouz, 
                       cov.keep="count")
emmdurcol <- data.frame(emmeans(durcol.lme, 
                                spec= 'count', 
                                level= 0.95))

durcol<-ggplot(data=emmdurcol,aes(x=count,y=exp(emmean)) ) +
    geom_point(data=summytrips,aes(x=count,y=TripDurh,color=year),
               shape=16,alpha=0.3)+
    geom_line(size=1.5) +
    geom_ribbon(data=emmdurcol,aes( x=count,
                                     ymin=exp(lower.CL),
                                     ymax=exp(upper.CL)),
                alpha=0.5,colour = NA) +
    scale_y_continuous(limits=c(0,200),
                       breaks=seq(0,200,50),
                       expand=c(0.01,0.01))+
    scale_x_continuous(limits=c(11, 23),
                       breaks=seq(11,23,4),
                       expand=c(0.01,0.01))+
    labs(y="Trip duration (h)",
         tag="b)",
         x="Colony size (x1000 ind)") +
    scale_colour_manual(values=mycol) +
    theme_light() +
    theme(#legend.position="none",
        panel.grid.minor = element_blank()) 

print(durcol)


tot.col.lme.rouz<-lme(log(TotalPathkm) ~ count, 
                      random=~1 | id , 
                      data=summytrips)
totcol.lme <- ref_grid(tot.col.lme.rouz, 
                       cov.keep= "count")
emmtotcol <- data.frame(emmeans(totcol.lme, 
                                spec= 'count', 
                                level= 0.95))

totcol<-ggplot(data=emmtotcol,aes(x=count,y=exp(emmean)) ) +
    geom_point(data=summytrips,aes(x=count,y=TotalPathkm,color=year),
               shape=16,alpha=0.3)+
    geom_line(size=1.5) +
    geom_ribbon(data=emmtotcol,aes( x=count,
                                    ymin=exp(lower.CL),
                                    ymax=exp(upper.CL)),
                alpha=0.5,colour = NA) +
    scale_y_continuous(limits=c(0,1400),
                       breaks=seq(0,1400,200),
                       expand=c(0.01,0.01))+
    scale_x_continuous(limits=c(11, 23),
                       breaks=seq(11,23,4),
                       expand=c(0.01,0.01))+
    labs(y="Total distance travelled (km)",
         tag="c)",
         x="") +
    scale_colour_manual(values=mycol,
                        name="Year") +
    theme_light() +
    theme(#legend.position="none",
        panel.grid.minor = element_blank()) 

print(totcol)
mylegendyear<-g_legend(totcol)

tiff(here::here("outputs","Predictions_trip_characteristics_2005-2023_colonysize.png"),
     width=6000,height=4000,res=600,
     compression="lzw")

grid.arrange(arrangeGrob(distcol+theme(legend.position="none"),
                         durcol+theme(legend.position="none"),
                         totcol+theme(legend.position="none"),
                         nrow=1,ncol=3),
             mylegendyear, ncol=2,widths=c(1,0.1)) 
dev.off()

```

# Test sex

```{r}

trips.sex<-all.trips %>% 
    dplyr::filter(!is.na(sex) & year!="2013") %>% 
    droplevels() 
    
table(trips.sex[,c("year","sex")])

newdatrouz<-expand.grid(day=seq(min(trips.sex$Date),
                                max(trips.sex$Date),1),
                        year=as.factor(unique(trips.sex$year)),
                        sex=as.factor(unique(trips.sex$sex)))
#glme on distance
glmm.dist.sex<-lme(log(Distmaxkm) ~ year+sex + Date, 
                        random=~1 | id , 
                        data=trips.sex)

summary(glmm.dist.sex)
anova(glmm.dist.sex)

#check effects
plot_model(glmm.dist.sex,sort.est = TRUE,show.values = TRUE)
ggpredict(glmm.dist.sex, terms = "sex", type="fe")%>% plot()

#glme on duration
glmm.dur.sex<-lme(log(TripDurh) ~ Date + sex +year, 
                        random=~1 | id , 
                        data=trips.sex)

summary(glmm.dur.sex)

#check effects
plot_model(glmm.dur.sex, sort.est = TRUE,show.values = TRUE)
ggpredict(glmm.dur.sex, terms = "sex", type="fe")%>% plot()


#glme on duration
glmm.totpath.sex<-lme(log(TotalPathkm) ~ year + sex + Date, 
                        random=~1 | id , 
                        data=trips.sex)

summary(glmm.totpath.sex)

#check effects
plot_model(glmm.totpath.sex, sort.est = TRUE,show.values = TRUE)
ggpredict(glmm.totpath.sex, terms = "sex", type="fe")%>% plot()





```
