---
title: "Analysis 2023 - Manuscript"
author: "Aurore Ponchon"
format: html
editor: visual
---

# Trips summary for 2023

The first chunk calculates the trips summary and characteristics

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false

library(here)
library(tidyverse)
library(gridExtra)
library(nlme)
library(emmeans)
library(DHARMa)
library(kableExtra)
library(plotrix)
library(readxl)
library(FactoMineR)
library(corrr)
library(corrplot)
library(factoextra)
library(ggcorrplot)

source(here("R","trip_functions.R"))

mycolsex<-c("darkorchid4","cyan3") #"deepskyblue3"
mycol2.90<-viridis(n=2,begin=0,end=0.6,option="D")
mycol2.50<-viridis(n=2,begin=0.1,end=0.7,option="D")

#get trips
load(here::here("data","NewlyCreatedData","clean_10_locs_AD_rouzic23.RData"))
trips6<-trips_summary_ind(cleanLocs.rouzic23,
                                  colony=colo_coord_rouzic) %>% 
    dplyr::mutate(sero=as.factor(sero))

#time in colony
load(here("data","NewlyCreatedData","rawLocRouzic2023.Rdata"))
land<-raw_rouzic_2023 %>% 
    land_summary_ind(.,colony=colo_coord_rouzic) %>% 
    dplyr::filter(LandDurh > 1 & 
                    LandDurh < 100 & 
                      stage=="adult") %>% 
     dplyr::mutate(sero=as.factor(sero))

#merge serological status
serol.rouzic<-get_serol_data_2023()   
             
#summary of all trips (26 adults)
trips<-trips6 %>% 
       mutate(day=as.numeric(as.Date(DateEnd) - as.Date("2023-07-02"))) %>% 
       droplevels() %>% 
              left_join(., serol.rouzic, by=c("id","sex","sero",
                                              "deploy","stage"),keep=F)

#summary of all periods on land
lands<-land %>% 
      mutate(day=as.numeric(as.Date(DateEnd) - as.Date("2023-07-02"))) %>% 
      droplevels() %>% 
      left_join(., serol.rouzic, by=c("id","sex","sero","deploy","stage"),keep=F)

# #get the 4 numerical variables which are used as proxies of body condition 
# mat<-trips %>% 
#     dplyr::distinct(id,body_weight,wing, culmen,tarsus, .keep_all = F) %>% 
#     dplyr::select(-id) %>% 
#     scale(.)
# 
# #check correlation between variables
# corr_matrix <- cor(mat)
# corrplot(corr_matrix, method="number")
# 
# #pca to calculate a body condition index
# data.pca <- princomp(mat)
# summary(data.pca)
# fviz_pca_var(data.pca, col.var = "cos2",
#             gradient.cols = c("black", "orange", "green"),
#             repel = TRUE)
# 
# #extract pca results
# cond<-get_pca_ind(data.pca)
# 
# #extract the axis 1 values
# IDS<-trips %>% 
#       dplyr::distinct(id,body_weight,wing, culmen, .keep_all = F) %>% 
#     dplyr::mutate(body_cond=cond$coord[,1])
# 
# #merge body condition index with rest of data
# trips.cond<-trips %>% 
#     left_join(.,IDS,by=c("id","body_weight","culmen","wing"))
# lands.cond<-lands %>% 
#     left_join(.,IDS,by=c("id","body_weight","culmen","wing"))



#Table summary for trips
sum.ids<-trips6 %>% 
    group_by(sero) %>% 
    summarize(Ids=length(unique(id)),
              Trips=length(unique(trip.id)),
              Debut=min(DateEnd),
              Fin=max(DateEnd)) 
  
kbl(sum.ids,caption="Sample size for trips") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

nb.trips.sum<-trips6 %>% 
    group_by(sero,id) %>% 
    summarize(Trips=mean(difftime(max(DateEnd),min(DateStart),units="days"))) %>% 
    summarize(cc=mean(Trips),
              SE=std.error(Trips),
              Min=min(Trips),
              Max=max(Trips))


nb.trips<-trips6 %>% 
     group_by(id, sero) %>% 
     count() %>% 
     group_by(sero) %>% 
     summarize(Min=min(n),
               Max=max(n))

sum.id<- trips6 %>% 
    group_by(id,sero) %>% 
    summarize(across(c(Distmaxkm, TripDurh, TotalPathkm), 
                     ~ mean(.x, na.rm = TRUE))) %>% 
    as.data.frame()

sum.trips1<- sum.id %>% 
    group_by(sero) %>% 
    summarize(across(where(is.numeric), 
                     list(Mean=mean,
                          SE=plotrix::std.error,
                          Min=min,
                          Max=max))) %>% 
    mutate(across(where(is.numeric), round,digits=1))


sum.trips<-sum.trips1 %>% 
    group_by(sero) %>% 
           dplyr::mutate(MeanDist=paste(Distmaxkm_Mean,Distmaxkm_SE,sep=" ± "),
                         DistRange=paste(Distmaxkm_Min,Distmaxkm_Max,sep=" - "),
                         MeanDur=paste(TripDurh_Mean,TripDurh_SE,sep=" ± "),
                         DurRange=paste(TripDurh_Min,TripDurh_Max,sep=" - "),     
                         MeanPath=paste(TotalPathkm_Mean,TotalPathkm_SE,sep=" ± "),
                      PathRange=paste(TotalPathkm_Min,TotalPathkm_Max,sep=" - ")) %>%
        dplyr::select(-c(2:13))

lands.ids<-land %>% 
    summarize(Ids=length(unique(id)),
              Land=length(unique(onland.id)),
              Debut=min(DateEnd),
              Fin=max(DateEnd))

kbl(lands.ids,caption="Sample size for periods on land") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

land.id<- land %>% 
    group_by(sero,id) %>% 
    summarize(Time= mean(LandDurh, na.rm=T)) %>% 
    as.data.frame()

sum.lands<- land.id %>% 
    group_by(sero) %>% 
    summarize(across(where(is.numeric), 
                     list(mean=mean,
                          se=plotrix::std.error))) %>% 
    mutate(across(where(is.numeric), round,digits=1)) 

kbl(sum.trips,caption="Summary of trip characteristics - Gaps <6h",
    col.names=c("Sero",
                "Maximal distance (km)",
                "Maximal distance (km)",
                "Trip Duration (h)",
                "Trip Duration (h)",
                "Total path (km)",
                "Total path (km)")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

kbl(sum.lands,caption="Summary of nest attendance",
    col.names=c("Sero","DurationMean","DurationSE")) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


```

# Statistical analysis 2023

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false

source(here::here("R","stats_functions.R"))
var<-c('day','sex','sero')

#summary of all trips (26 adults)
trips<-trips %>% 
       mutate(day=as.numeric(as.Date(DateEnd) - as.Date("2023-07-02")))

lands<-lands %>% 
      mutate(day=as.numeric(as.Date(DateEnd) - as.Date("2023-07-02")))


#daysx<-c("03/07","20/08","30/08","09/09","19/09","29/09","20/10")
newdat<-expand.grid(site=unique(trips$site),
                    day=seq(min(trips$day),
                            max(trips$day),1),
                    sero=unique(trips$sero),
               # body_cond=seq(-2.1,3.3,0.1),
                    sex=unique(trips$sex))

newdatland<-expand.grid(site=unique(trips$site),
                    day=seq(min(trips$day),
                            max(trips$day),1),
                    sero=unique(trips$sero),
                #    body_cond=seq(-2.1,3.3,0.1),
                    sex=unique(trips$sex))


glm.dist1<-lme(sqrt(Distmaxkm) ~ day + sex*sero ,
              random= ~1| id,
              data=trips)

glm.dist2<-lme(sqrt(Distmaxkm) ~ day + sex+sero,
              random= ~1| id,
              data=trips)

glm.dist3<-lme(sqrt(Distmaxkm) ~ day + sex + sero,
              random= ~1| id,
              data=trips)

glm.dist4<-lme(sqrt(Distmaxkm) ~ day + sex ,
              random= ~1| id,
              data=trips)

AIC(glm.dist1,glm.dist2,glm.dist3,glm.dist4)


summary(glm.dist2)
anova(glm.dist2)

qqnorm(resid(glm.dist4))
qqline(resid(glm.dist4))


glm.dur1<-lme(sqrt(TripDurh) ~ day + sex*sero ,
              random= ~1| id,
              data=trips)

glm.dur2<-lme(sqrt(TripDurh) ~ day + sex+sero,
              random= ~1| id,
              data=trips)

glm.dur3<-lme(sqrt(TripDurh) ~ day + sex + sero,
              random= ~1| id,
              data=trips)

glm.dur4<-lme(sqrt(TripDurh) ~ day + sex ,
              random= ~1| id,
              data=trips)

AIC(glm.dur1,glm.dur2,glm.dur3,glm.dur4)

summary(glm.dur3)
anova(glm.dur3)

qqnorm(resid(glm.dur4))
qqline(resid(glm.dur4))


##stats for total path
glm.path1<-lme(sqrt(TotalPathkm) ~ day + sex*sero ,
              random= ~1| id,
              data=trips)

glm.path2<-lme(sqrt(TotalPathkm) ~ day + sex+sero,
              random= ~1| id,
              data=trips)

glm.path3<-lme(sqrt(TotalPathkm) ~ day + sex + sero,
              random= ~1| id,
              data=trips)

glm.path4<-lme(sqrt(TotalPathkm) ~ day + sex ,
              random= ~1| id,
              data=trips)

AIC(glm.path1,glm.path2,glm.path3,glm.path4)

summary(glm.path2)
anova(glm.path2)

qqnorm(resid(glm.path4))
qqline(resid(glm.path4))

##stats for time on land
glm.land1<-lme(sqrt(LandDurh)~ day + sex*sero,
              random= ~1| id,
              data=lands)

glm.land2<-lme(sqrt(LandDurh)~ day + sex+sero,
              random= ~1| id,
              data=lands)

glm.land3<-lme(sqrt(LandDurh)~ day + sex + sero,
              random= ~1| id,
              data=lands)

glm.land4<-lme(sqrt(LandDurh)~ day + sex,
              random= ~1| id,
              data=lands)

glm.land5<-lme(sqrt(LandDurh)~ day ,
              random= ~1| id,
              data=lands)

AIC(glm.land1,glm.land2,glm.land3,glm.land4,glm.land5)


summary(glm.land3)
anova(glm.land3)

qqnorm(resid(glm.land5))
qqline(resid(glm.land5))


#predict fitted values and CI
var<-c('day','sex')


predist<-predict_lme_results(glm.dist4,newdat,var)
preddur<-predict_lme_results(glm.dur4,newdat,var)
predpath<-predict_lme_results(glm.path4,newdat,var)
predland<-predict_lme_results(glm.land4,newdatland,var)

#mycol<-viridis(n=2)

distlmmsex<-ggplot(trips, aes(x=day, y=Distmaxkm ,colour=sex)) + 
    geom_ribbon(data= data.frame(predist),
            aes(ymin= lower.CL^2, ymax= upper.CL^2,
                y= NULL,
                fill=sex),
           alpha=0.4,colour = NA) +
geom_point(alpha=0.4) +
 geom_line(data=predist,aes(x=day,y=emmean^2),lwd=1.5) +
     labs(y="Maximal distance to the colony (km)",tag="a)",x="") +
    scale_x_continuous(limits=c(0,110),
                     #  labels=daysx,
                       breaks=seq(0,120,20),
                       expand=c(0.001,0.001),
                     labels=c("02/07","22/07","11/08","31/08","20/09","10/10","30/10")) +
     scale_y_continuous(limits=c(0,400,100),
                        breaks=seq(0,400,100),
                        expand=c(0.001,0.001)) + 
 scale_colour_manual(values=mycol,name="Sex") +
 scale_fill_manual(values=mycol,name="Sex")  +
     theme_light()+
    theme(#legend.position="none",
          panel.grid.minor = element_blank()) 

durlmmsex<-ggplot(trips, aes(x=day, y=TripDurh ,colour=sex)) + 
    geom_ribbon(data= data.frame(preddur), 
            aes(ymin= lower.CL^2, ymax= upper.CL^2, 
                y= NULL,
                fill=sex), 
            alpha=0.4,colour = NA) +
geom_point(alpha=0.4) +
 geom_line(data=preddur,aes(x=day,y=emmean^2),lwd=1.5) +
     labs(y="Trip Duration (h)",tag="b)",x="") +
    scale_x_continuous(limits=c(0,110),
                     #  labels=daysx,
                       breaks=seq(0,120,20),
                       expand=c(0.001,0.001),
                     labels=c("02/07","22/07","11/08","31/08","20/09","10/10","30/10")) +
    scale_y_continuous(limits=c(0,200),
                       breaks=seq(0,200,50),
                       expand=c(0.001,0)) +
  scale_colour_manual(values=mycol,name="Sex") +
    scale_fill_manual(values=mycol,name="Sex")  +
    theme_light()+
    theme(#legend.position="none",
          panel.grid.minor = element_blank()) 
    

pathlmmsex<-ggplot(trips, aes(x=day, y=TotalPathkm ,colour=sex)) + 
    geom_ribbon(data= data.frame(predpath), 
            aes(ymin= lower.CL^2, ymax= upper.CL^2, 
                y= NULL,
                fill=sex), 
            alpha=0.4,colour = NA) +
geom_point(alpha=0.4) +
 geom_line(data=predpath,aes(x=day,y=emmean^2),lwd=1.5) +
     labs(y="Total distance travelled (km)",tag="c)",x="") +
    scale_x_continuous(limits=c(0,110),
                     #  labels=daysx,
                       breaks=seq(0,120,20),
                       expand=c(0.001,0.001),
                     labels=c("02/07","22/07","11/08","31/08","20/09","10/10","30/10")) +
    scale_y_continuous(limits=c(0,1200),
                       breaks=seq(0,1200,300),
                       expand=c(0.001,0)) +
  scale_colour_manual(values=mycol,name="Sex") +
    scale_fill_manual(values=mycol,name="Sex")  +
    theme_light()+
    theme(#legend.position="none",
          panel.grid.minor = element_blank()) 
    

landlmmsex<-ggplot(lands, aes(x=day, y=LandDurh ,colour=sex)) + 
    geom_ribbon(data= data.frame(predland), 
            aes(ymin= lower.CL^2, ymax= upper.CL^2, 
                y= NULL,
                fill=sex), 
            alpha=0.4,colour = NA) +
geom_point(alpha=0.4) +
 geom_line(data=predland,aes(x=day,y=emmean^2),lwd=1.5) +
     labs(y="Nest attendance (h)",tag="d)",x="") +
    scale_x_continuous(limits=c(0,110),
                     #  labels=daysx,
                       breaks=seq(0,120,20),
                       expand=c(0.001,0.001),
                     labels=c("02/07","22/07","11/08","31/08","20/09","10/10","30/10")) +
    scale_y_continuous(limits=c(0,60),
                       breaks=seq(0,60,15),
                       expand=c(0.001,0)) +
  scale_colour_manual(values=mycol,name="Sex") +
    scale_fill_manual(values=mycol,name="Sex")  +
    theme_light()+
    theme(panel.grid.minor = element_blank()) 
    
mylegendlmmsero<-g_legend(distlmmsex)

tiff(here("outputs","LMM_predictions_sex_2023_final.tif"),
     width=7000,
     height=4000,
     res=600,
     compression="lzw")
grid.arrange(arrangeGrob(distlmmsex+ theme(legend.position="none"),
                         durlmmsex+ theme(legend.position="none"),
                         pathlmmsex+ theme(legend.position="none"),
                         landlmmsex+ theme(legend.position="none") ,
                                     ncol=2),
               mylegendlmmsero, ncol=2,widths=c(1,0.1)) 

dev.off()
```

# Spatial analysis 2023

```{r}
#| echo: false
#| include: true
#| warning: false
#| message: false


library(sf)
library(adehabitatHR)
library(rnaturalearth)
library(terra)
library(raster)
library(ggspatial)
library(RColorBrewer)


source(here::here("R","trip_functions.R"))
source(here::here("R","problem_trips.R"))
source(here::here("R","spatial_function_KUD.R"))

#select locs for 2023
ind.var<-cleanLocs.rouzic23 %>% 
    dplyr::select(id,year,stage,period,sex,
                  age_chick,sero,travelNb,trip.id) %>% 
    group_by(id,year) %>% 
    slice(1) %>% 
    dplyr::filter(year==2023) %>% 
    droplevels() %>% 
    ungroup()

#get interpolated data from HMM
interp.23<- read_delim(here::here("data","RawData",
                               "HMM_Rouzic_Morus_bassanus_all_corrected.csv"), 
                  col_names=T,
                  delim = ";",
                  col_types = cols(indID = col_character(), 
                                    datetime = col_datetime(format = 
                                                                "%d/%m/%Y %H:%M"),
                                   longitude=col_number(),
                                   latitude=col_number()), 
                   trim_ws = TRUE) %>% 
    dplyr::rename(long=longitude,lat=latitude) %>% 
    dplyr::mutate(id=as.factor(str_sub(indID,-6,-1))) %>% 
    left_join(.,ind.var,by=c("id","year")) %>% 
    dplyr::filter(year==2023) %>% 
    droplevels() %>% 
    as.data.frame(.) 


#filter and project trips

locs.df23<-interp.23 %>%   #cleanLocs.rouzic23 %>% 
    dplyr::mutate(sero=sero,
                 #  deploy=as.factor(deploy),
                  sex=sex) %>% 
    dplyr::filter(!trip.id %in% migration & 
                      !trip.id %in% last.incomplete) %>% 
    droplevels() %>% 
      sf::st_as_sf(., coords = c("long","lat")) %>%
    sf::st_set_crs(4326) %>%
    st_transform(., projcrs) %>%
   dplyr::mutate(long = sf::st_coordinates(.)[,1],
                 lat = sf::st_coordinates(.)[,2]) %>% 
    as.data.frame(.)


locs.spdf23<-interp.23 %>%  #cleanLocs.rouzic23 %>% 
     dplyr::mutate(sero=sero,
                   #deploy=as.factor(deploy),
                   sex=sex) %>% 
    dplyr::filter(!trip.id %in% migration & 
                      !trip.id %in% last.incomplete) %>% 
    droplevels() %>%
    sf::st_as_sf(., coords = c("long","lat")) %>%
    sf::st_set_crs(4326) %>%
    st_transform(., projcrs) %>%
    as_Spatial(.)

#rm(cleanLocs.rouzic23)

#load bathymetry layer


#get reduced dataframes 
locs.fem.df23<-get_df_filtered(locs.df23,sex,"F") 
locs.mal.df23<-get_df_filtered(locs.df23,sex,"M") 

locs.pos.df23<-get_df_filtered(locs.df23,sero,"1") 
locs.neg.df23<-get_df_filtered(locs.df23,sero,"0") 

#get dataframes as ltraj for brb function
locs.ltr.fem23<-as.ltraj(locs.fem.df23[,c("long","lat")], 
             date=locs.fem.df23$datetime, 
             id=locs.fem.df23$id,
             typeII = TRUE)

locs.ltr.mal23<-as.ltraj(locs.mal.df23[,c("long","lat")], 
             date=locs.mal.df23$datetime, 
             id=locs.mal.df23$id,
             typeII = TRUE)

#get dataframes as ltraj for brb function
locs.ltr.pos23<-as.ltraj(locs.pos.df23[,c("long","lat")], 
             date=locs.pos.df23$datetime, 
             id=locs.pos.df23$id,
             typeII = TRUE)

locs.ltr.neg23<-as.ltraj(locs.neg.df23[,c("long","lat")], 
             date=locs.neg.df23$datetime, 
             id=locs.neg.df23$id,
             typeII = TRUE)



##kernels with normal ud

# locs.fem.spdf<-subset(locs.spdf , locs.spdf$sex=="F") 
# locs.mal.spdf<-subset(locs.spdf , locs.spdf$sex=="M") 
# KUD.sero.mal<- kernelUD(locs.mal.spdf,
#                     same4all=T,
#                     h=7500,
#                     grid=1000)
# 
# KUD.sero.fem<- kernelUD(locs.fem.spdf,
#                     same4all=T,
#                     h=7500,
#                     grid=1000)
# 
BA.KUD.90<-kerneloverlap(locs.spdf23[,"sero"], grid=500,meth="BA",percent=90)
# BA.KUD.50<-kerneloverlap(locs.spdf[,"sex"], grid=1000,meth="BA",percent=50)



##kernels with brb
TMAX=3600
LMIN=50
HMIN=10000
GRID=500

#get D parameters for BRB function
Tmal23<-BRB.D(locs.ltr.mal23, Tmax = TMAX, Lmin = LMIN)
Tfem23<-BRB.D(locs.ltr.fem23, Tmax = TMAX, Lmin = LMIN)
Tpos23<-BRB.D(locs.ltr.pos23, Tmax = TMAX, Lmin = LMIN)
Tneg23<-BRB.D(locs.ltr.neg23, Tmax = TMAX, Lmin = LMIN)


#BRB function
KUD.mal23<-get_brb_raster(locs.ltr.mal23,Tmal23,
                        TMAX,LMIN,
                        HMIN,GRID)
KUD.fem23<-get_brb_raster(locs.ltr.fem23,Tfem23,
                        TMAX,LMIN,
                        HMIN,GRID)

KUD.pos23<-get_brb_raster(locs.ltr.pos23,Tpos23,
                        TMAX,LMIN,
                        HMIN,GRID)
KUD.neg23<-get_brb_raster(locs.ltr.neg23,Tneg23,
                        TMAX,LMIN,
                        HMIN,GRID)

ver.mal23.90<-st_as_sf(getverticeshr(KUD.mal23, percent=90),crs = projcrs) %>% 
    mutate(Sex="90M")
ver.mal23.50<-st_as_sf(getverticeshr(KUD.mal23, percent=50),crs = projcrs)%>% 
    mutate(Sex="50M")
ver.fem23.90<-st_as_sf(getverticeshr(KUD.fem23, percent=90),crs = projcrs)%>% 
    mutate(Sex="90F")
ver.fem23.50<-st_as_sf(getverticeshr(KUD.fem23, percent=50),crs = projcrs)%>% 
    mutate(Sex="50F")


ver.pos23.90<-st_as_sf(getverticeshr(KUD.pos23, percent=90),crs = projcrs)%>% 
    mutate(Sero="90+")
ver.pos23.50<-st_as_sf(getverticeshr(KUD.pos23, percent=50),crs = projcrs)%>% 
    mutate(Sero="50+")
ver.neg23.90<-st_as_sf(getverticeshr(KUD.neg23, percent=90),crs = projcrs)%>% 
    mutate(Sero="90-")
ver.neg23.50<-st_as_sf(getverticeshr(KUD.neg23, percent=50),crs = projcrs)%>% 
    mutate(Sero="50-")

#BA.KUD.90<-kerneloverlap(locs.spdf[,"sex"], grid=GRID,meth="BA",percent=90)


#extent of study area
    ext.brit<-terra::ext(300000,650000,5270000,5650000)
    
    bathym<-terra::rast(here::here("data",
                                   "RawData",
                                   "shapefiles",
                                   "Bathym_FR_UK.tif")) %>% 
        terra::project(.,projcrs) %>% 
        terra::crop(., ext.brit)
    
    bathym[bathym>0]<-0
    ocean.pal <- rev(colorRampPalette(brewer.pal(9,"Blues"))(9))
    zbreaks <- c(-500,-200,-150,-100,-50,-25,0)
    
    
    #select borders
    target<-c("France","United Kingdom","Spain","Belgium",
              "Netherlands", "Germany","Ireland","Isle of Man",
              "Jersey" ,"Guernsey"  ,"Åland")
    
    ##Plot maps
    #contours of countries
    shp<-ne_countries(scale = 10, returnclass = 'sf') %>%
        dplyr::filter(name %in% target) %>% 
        st_transform(.,projcrs)  %>% 
        st_crop(., ext.brit)
    
    #coastlines
    coast<-ne_coastline(scale = 10, returnclass = "sf") %>% 
        st_transform(.,projcrs)  %>% 
        st_crop(., ext.brit)
    
    #location of colony
    coord_rouzic<-colo_coord_rouzic %>% 
        sf::st_as_sf(., coords = c("long","lat")) %>% 
        sf::st_set_crs(4326) %>% 
        st_transform(.,projcrs)
    

#colors for plot
mycolsero<-c("#F6A173","#EA4C3B","#81C07A", "#004616")
mycolsex<-c("darkorchid1","darkorchid4","#60EFFF","#0093AF")


#plot
kern.sex23<-ggplot()+
        # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
        geom_sf(data=ver.fem23.90, aes(fill=Sex) , 
                colour=NA,
                alpha=0.2) + 
        geom_sf(data=ver.fem23.50, aes(fill=Sex) , #fill=mycolsex[2],
                colour=NA ,
                alpha=0.7) +
        geom_sf(data=ver.mal23.90, aes(fill=Sex), #fill=mycolsex[3],
                colour=NA,
                alpha=0.5) +
        geom_sf(data=ver.mal23.50, aes(fill=Sex) , #fill=mycolsex[1],
                colour=NA ,
                alpha=0.7) +
        geom_sf(data=shp,fill="grey90") +
        geom_sf(data=coast) +
        geom_sf(data = coord_rouzic,
                shape=23,
                colour="black",
                fill="yellow",
                size=4) +
        coord_sf(xlim=ext.brit[c(1,2)],
                 ylim=ext.brit[c(3,4)],
                 expand=F) +
        labs(tag="b)") +
        scale_fill_manual(values=c("50F"="darkorchid4",
                                   "50M"="#0093AF",
                                   "90F"="darkorchid1",
                                   "90M"="#60EFFF"),
                            labels=c("90F"="90% UD female",
                                     "50F"="50% UD female",
                                     "90M" = "90% UD male",
                                     "50M" = "50% UD male"),
                       #   levels=c("90F","50F","90M","50M"),
                            name="Sex") +
        annotation_scale(location = "br",
                         width_hint = 0.15,
                         pad_x = unit(0.7, "cm"),
                         bar_cols = "black") +
        annotation_north_arrow(location = "br",
                               which_north = "true",
                               style = ggspatial::north_arrow_nautical(),
                               pad_y = unit(0.8, "cm")) +
        theme_bw() +
      theme(legend.position="bottom")+
      guides(fill=guide_legend(ncol=2))
   
  
print(kern.sex23)



#plot
  kern.sero23<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
     geom_sf(data=ver.pos23.90, aes(fill=Sero) , 
                colour=NA,
                alpha=0.4) + 
        geom_sf(data=ver.pos23.50, aes(fill=Sero) , #fill=mycolsex[2],
                colour=NA ,
                alpha=0.7) +
        geom_sf(data=ver.neg23.90, aes(fill=Sero), #fill=mycolsex[3],
                colour=NA,
                alpha=0.4) +
        geom_sf(data=ver.neg23.50, aes(fill=Sero) , #fill=mycolsex[1],
                colour=NA ,
                alpha=0.5) +
   geom_sf(data=shp,fill="grey90") +
  geom_sf(data=coast) +
 geom_sf(data = coord_rouzic,
         shape=23,
         colour="black",
         fill="yellow",
         size=4) +
 coord_sf(xlim=ext.brit[c(1,2)],
          ylim=ext.brit[c(3,4)],
          expand=F) +  
  labs(tag="a)") +
        scale_fill_manual(values=c("50+"="#EA4C3B",
                                   "50-"="#004616",
                                   "90+"="#F6A173",
                                   "90-"="#81C07A"),
                            labels=c("90+"="90% UD sero+",
                                     "50+"="50% UD sero+",
                                     "90-" = "90% UD sero-",
                                     "50-" = "50% UD sero-"),
                       #   levels=c("90F","50F","90M","50M"),
                            name="Serology") +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw()+
      theme(legend.position="bottom")+
      guides(fill=guide_legend(ncol=2))
  
  print(kern.sero23)

   tiff(here::here("outputs","adults_distribution_brb_2023_final_legend.tif"),
     width=4000,
     height=2500,
     res=500,
     compression="lzw")

grid.arrange(kern.sero23,kern.sex23,ncol=2,nrow=1)

dev.off()


```

# Spatial analysis 2005-2022

```{r}


load(here::here("data","NewlyCreatedData",
                "clean_2_locs_AD_rouzic2005-2019.RData"))
load(here::here("data","NewlyCreatedData",
                "clean_locs_rouzic_2022.RData"))


rouz05.19<-cleanLocs.rouzic05.19 %>% 
    dplyr::select(id,datetime,long,lat,
                  distmax,distadj,totalpath,difftimemin,travelNb,
           onlandNb,trip.id) %>% 
    mutate(year=year(datetime)) 


#Identification of trips to exclude (incomplete trips and migration trip) for 2022
incomplete.2022<-c("222267.1","222267.6","222275.1","222276.1",
              "222279.8","222279.32","222280.45","222269.17","222270.32","222271.25","222272.24","222273.22","222274.25","222275.28","222276.17","222277.10","222278.1","222279.33","222280.46","222281.7")


rouz22<-cleanLocs.rouzic %>% 
    dplyr::filter(!trip.id %in% incomplete.2022) %>% 
    dplyr::select(id,datetime,long,lat,
                  distmax,distadj,totalpath,difftimemin,travelNb,
           onlandNb,trip.id) %>% 
     mutate(year=year(datetime)) 


rouz.all1<-rbind(rouz05.19,rouz22) 


metadata<-read_excel(here("data","RawData","metadata_2005-2023.xlsx"),
              sheet="Feuil1",col_names = T) %>% 
    dplyr::filter(year!=2023)

rouz.all<-rouz.all1%>% 
    left_join(.,metadata,by=c("year","id")) %>% 
    dplyr::mutate(id=as.factor(id),
                  trip.id=as.factor(trip.id),
                  sero=as.factor(sero)) %>% 
    dplyr::arrange(year,id,datetime)

#select locs for 2023
ind.var<-rouz.all %>% 
    dplyr::select(id,year,sex,travelNb,trip.id) %>% 
    group_by(id,year) %>% 
    slice(1) %>% 
    ungroup()

#get interpolated data from HMM
interp.0522<- read_delim(here::here("data","RawData",
                               "HMM_Rouzic_Morus_bassanus_all_corrected.csv"), 
                  col_names=T,
                  delim = ";",
                  col_types = cols(indID = col_character(), 
                                    datetime = col_datetime(format = 
                                                                "%d/%m/%Y %H:%M"),
                                   longitude=col_number(),
                                   latitude=col_number()), 
                   trim_ws = TRUE) %>% 
    dplyr::rename(long=longitude,lat=latitude) %>% 
    dplyr::mutate(id=as.factor(indID)) %>% 
      dplyr::filter(year!=2023) %>% 
    droplevels(.) %>% 
  #  left_join(.,ind.var,by=c("id","year")) %>% 
  
    as.data.frame(.) 



#filter and project trips

locs.df0522<-interp.0522 %>%   #cleanLocs.rouzic23 %>% 
    # dplyr::mutate(sero=sero,
    #              #  deploy=as.factor(deploy),
    #               sex=sex) %>% 
    # dplyr::filter(!trip.id %in% migration & 
    #                   !trip.id %in% last.incomplete) %>% 
   # droplevels() %>% 
      sf::st_as_sf(., coords = c("long","lat")) %>%
    sf::st_set_crs(4326) %>%
    st_transform(., projcrs) %>%
   dplyr::mutate(long = sf::st_coordinates(.)[,1],
                 lat = sf::st_coordinates(.)[,2]) %>% 
    as.data.frame(.)


locs.spdf0522<-interp.0522 %>%  #cleanLocs.rouzic23 %>% 
    #  dplyr::mutate(sero=sero,
    #                #deploy=as.factor(deploy),
    #                sex=sex) %>% 
    # dplyr::filter(!trip.id %in% migration & 
    #                   !trip.id %in% last.incomplete) %>% 
    # droplevels() %>%
    sf::st_as_sf(., coords = c("long","lat")) %>%
    sf::st_set_crs(4326) %>%
    st_transform(., projcrs) %>%
    as_Spatial(.)


#get reduced dataframes 
# locs.fem.df<-get_df_filtered(locs.df,sex,"F") 
# locs.mal.df<-get_df_filtered(locs.df,sex,"M") 
# 
# #get dataframes as ltraj for brb function
# locs.ltr.fem<-as.ltraj(locs.fem.df[,c("long","lat")], 
#              date=locs.fem.df$datetime, 
#              id=locs.fem.df$id,
#              typeII = TRUE)
# 
# locs.ltr.mal<-as.ltraj(locs.mal.df[,c("long","lat")], 
#              date=locs.mal.df$datetime, 
#              id=locs.mal.df$id,
#              typeII = TRUE)


locs.ltr.all<-as.ltraj(locs.df0522[,c("long","lat")], 
             date=locs.df0522$datetime, 
             id=locs.df0522$id,
             typeII = TRUE)


##kernels with normal ud

# locs.fem.spdf<-subset(locs.spdf , locs.spdf$sex=="F") 
# locs.mal.spdf<-subset(locs.spdf , locs.spdf$sex=="M") 
# KUD.sero.mal<- kernelUD(locs.mal.spdf,
#                     same4all=T,
#                     h=7500,
#                     grid=1000)
# 
# KUD.sero.fem<- kernelUD(locs.fem.spdf,
#                     same4all=T,
#                     h=7500,
#                     grid=1000)
# 
# BA.KUD.90<-kerneloverlap(locs.spdf[,"sex"], grid=1000,meth="BA",percent=90)
# BA.KUD.50<-kerneloverlap(locs.spdf[,"sex"], grid=1000,meth="BA",percent=50)

 BA.KUD.90<-kerneloverlap(locs.spdf0522[,"year"], grid=1000,meth="BA",percent=90)
 BA.KUD.50<-kerneloverlap(locs.spdf0522[,"year"], grid=1000,meth="BA",percent=50)

##kernels with brb
TMAX=3600
LMIN=50
HMIN=10000
GRID=500

#get D parameters for BRB function
# Tmal<-BRB.D(locs.ltr.mal, Tmax = TMAX, Lmin = LMIN)
# Tfem<-BRB.D(locs.ltr.fem, Tmax = TMAX, Lmin = LMIN)
Tall<-BRB.D(locs.ltr.all, Tmax = TMAX, Lmin = LMIN)

#BRB function
# KUD.mal<-get_brb_raster(locs.ltr.mal,Tmal,
#                         TMAX,LMIN,
#                         HMIN,GRID)
# KUD.fem<-get_brb_raster(locs.ltr.fem,Tfem,
#                         TMAX,LMIN,
#                         HMIN,GRID)

KUD.all<-get_brb_raster(locs.ltr.all,Tall,
                        TMAX,LMIN,
                        HMIN,GRID)
# 
# ver.mal.90<-st_as_sf(getverticeshr(KUD.mal, percent=90),crs = projcrs)
# ver.mal.50<-st_as_sf(getverticeshr(KUD.mal, percent=50),crs = projcrs)
# ver.fem.90<-st_as_sf(getverticeshr(KUD.fem, percent=90),crs = projcrs)
# ver.fem.50<-st_as_sf(getverticeshr(KUD.fem, percent=50),crs = projcrs)
ver.all.90<-st_as_sf(getverticeshr(KUD.all, percent=90),crs = projcrs)
ver.all.50<-st_as_sf(getverticeshr(KUD.all, percent=50),crs = projcrs)

#BA.KUD.90<-kerneloverlap(locs.spdf[,"sex"], grid=GRID,meth="BA",percent=90)


#extent of study area
ext.brit<-terra::ext(250000,650000,5270000,5650000)
bathym<-terra::rast(here::here("data",
                               "RawData",
                               "shapefiles",
                               "Bathym_FR_UK.tif")) %>% 
       terra::project(.,projcrs) %>% 
       terra::crop(., ext.brit)

bathym[bathym>0]<-0
ocean.pal <- rev(colorRampPalette(brewer.pal(9,"Blues"))(9))
zbreaks <- c(-500,-200,-150,-100,-50,-25,0)


#select borders
target<-c("France","United Kingdom","Spain","Belgium",
          "Netherlands", "Germany","Ireland","Isle of Man",
          "Jersey" ,"Guernsey"  ,"Åland")

##Plot maps
#contours of countries
shp<-ne_countries(scale = 10, returnclass = 'sf') %>%
    dplyr::filter(name %in% target) %>% 
  st_transform(.,projcrs)  %>% 
    st_crop(., ext.brit)

#coastlines
coast<-ne_coastline(scale = 10, returnclass = "sf") %>% 
  st_transform(.,projcrs)  %>% 
    st_crop(., ext.brit)

#location of colony
coord_rouzic<-colo_coord_rouzic %>% 
    sf::st_as_sf(., coords = c("long","lat")) %>% 
    sf::st_set_crs(4326) %>% 
    st_transform(.,projcrs)



#colors for plot
mycol90<-viridis(n=2,begin=0.2,end=0.8,option="D")
mycol50<-viridis(n=2,begin=0,end=0.6,option="D")


#plot
  kern.all<-ggplot()+
   # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
    geom_sf(data=ver.all.90, fill="grey50" ,
                             colour=NA,
                             alpha=0.7) + 
      geom_sf(data=ver.all.50, fill="grey10" ,
                             colour=NA ,
                             alpha=0.8) +
     #   geom_path(data=locs.df0522,aes(x=long,y=lat,group=year), alpha=0.2) +
   geom_sf(data=shp,fill="grey90") +
  geom_sf(data=coast) +
 geom_sf(data = coord_rouzic,
         shape=23,
         colour="black",
         fill="yellow",
         size=4) +
 coord_sf(xlim=ext.brit[c(1,2)],
          ylim=ext.brit[c(3,4)],
          expand=F) +
  labs(title="Distribution 2005 - 2022") +
    annotation_scale(location = "br",
                     width_hint = 0.15,
                     pad_x = unit(0.7, "cm"),
                     bar_cols = "black") +
    annotation_north_arrow(location = "br",
                           which_north = "true",
                           style = ggspatial::north_arrow_nautical(),
                           pad_y = unit(0.8, "cm")) +
    theme_bw() 

   tiff(here::here("outputs","adults_distribution_kernel_all_05_22_correct.tif"),
     width=3500,
     height=3500,
     res=500,
     compression="lzw")

print(kern.all)

dev.off()



#plot
#   kern.sex<-ggplot()+
#    # tidyterra::geom_spatraster(data = bathym, aes(fill =  Bathym_FR_UK)) +
#     geom_sf(data=ver.fem.90, fill=mycol2.90[1] ,
#                              colour=NA,
#                              alpha=0.2) + 
#       geom_sf(data=ver.mal.90, fill=mycol2.90[2] ,
#                              colour=NA ,
#                              alpha=0.2) +
#          geom_sf(data=ver.fem.50, fill=mycol2.50[1],
#                              colour=NA,
#                              alpha=0.6) +
#     geom_sf(data=ver.mal.50, fill=mycol2.50[2] ,
#                              colour=NA ,
#                              alpha=0.6) +
# 
#    geom_sf(data=shp,fill="grey90") +
#   geom_sf(data=coast) +
#  geom_sf(data = coord_rouzic,
#          shape=23,
#          colour="black",
#          fill="yellow",
#          size=4) +
#  coord_sf(xlim=ext.brit[c(1,2)],
#           ylim=ext.brit[c(3,4)],
#           expand=F) +
#   labs(title="Distribution males vs females") +
#     annotation_scale(location = "br",
#                      width_hint = 0.15,
#                      pad_x = unit(0.7, "cm"),
#                      bar_cols = "black") +
#     annotation_north_arrow(location = "br",
#                            which_north = "true",
#                            style = ggspatial::north_arrow_nautical(),
#                            pad_y = unit(0.8, "cm")) +
#     theme_bw() 
# 
#    tiff(here::here("outputs","adults_distribution_kernel_sex_05_22_correct.tif"),
#      width=3500,
#      height=3500,
#      res=500,
#      compression="lzw")
# 
# print(kern.sex)
# 
# dev.off()


```
