---
title: "Data processing 2005-2017"
author: "Aurore Ponchon"
format: html
editor: visual
---

## 1. Data processing from txt files 2005 and 2006

```{r}

library(here)
library(tidyverse)

gps_type1<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type1"),
                      full.names = T)
name.file1<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type1"),
                      full.names = F) %>% 
           str_remove(., ".TXT")

dat1.2005.2006<-NULL

for (i in 1:length(gps_type1)){
    print(i)
    
 file1<-read.table(gps_type1[i],
                   header=F,
                   skip=14,
                   sep=" ")

datetime<-as.POSIXct(paste(as.Date(file1$V1,format="%d.%m.%Y"),
                        file1$V2, 
                        sep=" "),
                     format="%F %H:%M:%S",tz="")

id<-name.file1[i]
 
tot<-data.frame(year=year(datetime),
                id=id,
                datetime=datetime,
                long=file1$V5,
                lat=file1$V3)

#account for differences in file format
if(max(as.numeric(tot$lat))>100){
    tot$long<-as.numeric(substr(tot$long, 1, 1)) + (as.numeric(substr(tot$long, 2, 7)) /60)
    tot$lat<-as.numeric(substr(tot$lat, 1, 2)) + (as.numeric(substr(tot$lat, 3, 7)) /60)
}

tot$long<-ifelse(file1$V6=="W",-tot$long,tot$long)
   
plot(tot$long,tot$lat,
     pch=16,
     main=tot$id[1])


dat1.2005.2006<-rbind(dat1.2005.2006,tot)    
}
```

## 2. Data processing from log files 2005 and 2006

```{r}
gps_type2<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type2"),
                      full.names = T)
name.file2<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type2"),
                      full.names = F) %>% 
           str_remove(., ".log") %>% 
          str_replace(.,"-",".")

dat2.2005.2006<-NULL

for (i in 1:length(gps_type2)){
    print(i)
    
 file2<-read.table(gps_type2[i],
                   header=F,
                   skip=2)

datetime<-as.POSIXct(paste(as.Date(file2$V8,format="%m/%d/%Y"),
                        file2$V7, 
                        sep=" "),
                     format="%F %H:%M:%S",tz="")

id<-name.file2[i]
 
tot<-data.frame(year=year(datetime),
                id=id,
                datetime=datetime,
                long=file2$V16,
                lat=file2$V17)

plot(tot$long,tot$lat,
     pch=16,
     main=tot$id[1])


dat2.2005.2006<-rbind(dat2.2005.2006,tot)    
}
```

# 3. Data processing 2006/2010

```{r}

gps_type3<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type3"),
                      full.names = T)
name.file3<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type3"),
                      full.names = F) %>% 
           str_remove(., ".txt") %>% 
           str_remove(., "GPS-") %>% 
           str_replace(.,"-",".")

dat3.2010<-NULL

for (i in 1:length(gps_type3)){
    print(i)
    
 file3<-read.table(gps_type3[i],
                   header=F)

datetime<-as.POSIXct(paste(as.Date(file3$V2,format="%d/%m/%Y"),
                        file3$V1, 
                        sep=" "),
                     format="%F %H:%M:%S",tz="")

id<-name.file3[i]
 
tot<-data.frame(year=year(datetime),
                id=id,
                datetime=datetime,
                long=file3$V3,
                lat=file3$V4) %>% 
    filter(row_number() %% 30 == 1)

plot(tot$long,tot$lat,
     pch=16,
     main=tot$id[1])


dat3.2010<-rbind(dat3.2010,tot)    
}
```

# 4. Data processing 2011-2017

```{r}
gps_type4<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type4"),
                      full.names = T)
name.file4<-list.files(here::here("data","RawData","GPS ROUZIC","GPS_type4"),
                      full.names = F) %>% 
           str_remove(., ".csv") %>% 
           str_remove(., "-Rouzic") %>% 
           str_replace(.,"-",".")

dat4.2011.2017<-NULL

for (i in 1:length(gps_type4)){
    print(i)
    
 file4<-read.table(gps_type4[i],
                   header=T,
                   sep=",")

datetime<-as.POSIXct(paste(as.Date(file4$Date,format="%Y/%m/%d"),
                        file4$Time, 
                        sep=" "),
                     format="%F %H:%M:%S",tz="")

id<-name.file4[i]
 
tot<-data.frame(year=year(datetime),
                id=id,
                datetime=datetime,
                long=file4$Longitude,
                lat=file4$Latitude) 

plot(tot$long,tot$lat,
     pch=16,
     main=tot$id[1])


dat4.2011.2017<-rbind(dat4.2011.2017,tot)    
}
```

# 5. Merging all data

```{r}
all.dat<-rbind(dat1.2005.2006,dat2.2005.2006,dat3.2010,dat4.2011.2017)
```
